config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy'
  resources :articles do
    member do
      get :summary
    end
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  # POST articles/:id/likes
  # POST likes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :banner, BannerUploader
	
	has_many :comments, dependent: :destroy
	has_many :likes
	has_many :articles, through: :likes
	belongs_to :author, class_name: "User"


	validates :title, presence: true, length: { minimum: 2 }

	def tags=(value)
		value = sanitize_tags(value) if value.is_a?(String)
		super(value)
	end

	private

	def sanitize_tags(value)
		value.downcase.split.uniq
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, email: true, presence: true
  validates :body, presence: true, length: { in: 6..500 }
end

app/models/like.rb
class Like < ApplicationRecord

belongs_to :user
belongs_to :article

validates :user, uniqueness: { scope: :article }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :articles, foreign_key: :author_id

         has_many :likes
         has_many :liked_articles, through: :likes, source: :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy, :summary]
  before_action :authorize_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.includes(:author).order(created_at: :desc)
    @articles = @articles.where("? = any(tags)", params[:q]) if params[:q].present?
      respond_to do |format|
        format.json do
          render json: @articles
end
          format.html do
            render
        end
      end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permitted_attributes(Article))
    @article.author = current_user
    if @article.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @like = Like.find_or_initialize_by(article: @article, user: current_user)
  end

  def edit
  end

  def update
    if @article.update(permitted_attributes(@article))
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

 def summary
    respond_to do |format|
      format.json do
        render json: {
          id: @article.id,
          likes: @article.likes.count,
          comments: @article.comments.count
        }
      end
    end
  end

  private

  def authorize_article
    authorize @article
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    comment_params = params.require(:comment).permit(:commenter, :body)
    @comment = Comment.new(article_id: @article.id)
    @comment.attributes = comment_params
    if @comment.save
      UserMailer.article_commented(@article).deliver_later
      redirect_to article_path(@comment.article)
    else
      @like = Like.find_or_initialize_by(article: @article, user: current_user)
      render 'articles/show'
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to article_path(@comment.article)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		like = Like.new(article_id: params[:article_id], user: current_user)

		like.save
		redirect_to article_path(like.article)

	end

	def destroy
		like = Like.find(params[:id])
		like.destroy

		redirect_to article_path(like.article)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_error_messages.html.erb
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<%= render 'error_messages' %>
<div class="form-group">
  <%= f.label :title %>
<%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :text %>
<%= f.text_area :text, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :tags %>
<%= f.text_field :tags, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :banner %>
<%= f.file_field :banner, class: "form-control" %>
</div>
<div class="form-group">
<%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1><p style="color: red">List Articles</p></h1>


<%= form_tag articles_path, method: :get do %>
  <div class="input-group">
    <%= text_field_tag :q, params[:q], class: "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: "btn btn-default" %>
    </span>
  </div>
<% end %>

	<div class="list-group>"
	<% @articles.each do |article| %>
<div class="list-group-item">
<h4 class="list-group-item-heading"><%= article.title %></h4>
<div class="list-group-item-text">
<%= article.text %>
</div>
<div class="list-group-item-text">
<%= article.author.email %>

<div class="list-group-item-text">
<%= link_to "Show", article_path(article), class: "btn btn-xs btn-primary" %>

<% if article.author == current_user %>

<%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
<%= link_to "Destroy", article_path(article),
method: :delete, data: { confirm: "Are you sure?" },
class: "btn btn-xs btn-danger" %>
<% end %>
<%= link_to "Summary", summary_article_path(article), class: "btn btn-xs btn-primary summary", id: "summary-#{article.id}" %>

</div>
</div>
	<% end %>
</div>
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1><p style="color: red" New Article</p></h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><p style="color: green">
	Article</p>
</h1>

<%= image_tag @article.banner %>
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Tekst:</strong>
	<%= @article.text %>
</p>
<br>

<%= pluralize(@article.likes.count, "person") %> liked this article

<% if @like.persisted? %>

<%= link_to "Unlike",  article_like_path(@article, @like), method: :delete %>
<% else %>
<%= link_to "Like",  article_likes_path(@article), method: :post %>


<% end %>


<h3><p style="color: blue">Comments</p></h3>

<% @article.comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
<% end %>

<%= render 'comments/form' %>


<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <%= link_to 'Destroy', article_comment_path(comment.article, comment),
     method: :delete,
              data: { confirm: 'Are you sure?' } %>
	

app/views/comments/_form.html.erb
<%= form_for([@article, @comment]) do |f| %>
<%= render 'common/error_messages', model: @comment %>

<%= f.hidden_field :article_id %>
<div class="form-group">
<%= f.label :commenter %>
<%= f.text_field :commenter, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :body %>
<%= f.text_area :body, class: "form-control" %>
</div>
<div class="form-group">
<%= f.submit class: "btn btn-primary"%>
</div>

<% end %>

app/views/common/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(model.errors.count, "error") %> prohibited
        this <%= model.class %> from being saved:
    </h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
   <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert danger">
        <%= alert %>
      </div>
    <% end %>

<% if user_signed_in? %>
  
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  <% end %>
    <div class="container">

    	<%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome from Rails</h1>

<%= link_to 'My blog', articles_path %>
<input type="text" id="field1" />
<input type="text" id="field2" />
<button id="add">Dodaj</button>
<p id="wynik">
	</p>